service: cloud-log-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
  vpc:
    securityGroupIds:
      - sg-01ad9de92d33418af 
    subnetIds:
      - subnet-057acc8c585ba8059

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: 
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Accept
            allowCredentials: false