service: cloud-log-api
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30  
  environment:
    DB_HOST: '{{resolve:secretsmanager:CLDB:SecretString:DB_HOST}}'
    DB_USER: '{{resolve:secretsmanager:CLDB:SecretString:DB_USER}}'
    DB_PASSWORD: '{{resolve:secretsmanager:CLDB:SecretString:DB_PASSWORD}}'
    DB_NAME: '{{resolve:secretsmanager:CLDB:SecretString:DB_NAME}}'
    JWT_SECRET: '{{resolve:secretsmanager:CLDB:SecretString:JWT_SECRET}}'
    CORS_ORIGINS: '{{resolve:secretsmanager:CLDB:SecretString:CORS_ORIGINS}}'     
  vpc:
    securityGroupIds:
      - sg-0b18501d058f04fb3
    subnetIds:
      - subnet-057acc8c585ba8059
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - "arn:aws:secretsmanager:us-east-1:*:secret:CLDB*"

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin:
              - 'https://main.d28k95mqep4uke.amplifyapp.com'
            allowCredentials: true
            headers:
              - Content-Type
              - Authorization
            methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

resources:
  Resources:
    SecretsManagerVpcEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
        VpcEndpointType: Interface
        VpcId: vpc-076853da424103843
        SubnetIds:
          - subnet-057acc8c585ba8059
        SecurityGroupIds:
          - sg-0b18501d058f04fb3
        PrivateDnsEnabled: true